print("STUDENT BIODATA")
print("----------------")

name = input("Enter Name: ")
age = input("Enter Age: ")
gender = input("Enter Gender: ")
course = input("Enter Course: ")
department = input("Enter Department: ")
college = input("Enter College Name: ")
phone = input("Enter Phone Number: ")
email = input("Enter Email ID: ")

print("\n--- BIODATA ---")
print("Name       :", name)
print("Age        :", age)
print("Gender     :", gender)
print("Course     :", course)
print("Department :", department)
print("College    :", college)
print("Phone No   :", phone)
print("Email ID   :", email)
